### ISSUE TITLE
Can't run with `--net=host`

### ISSUE THREAD

**Issue by vitorarins** [gocd/docker-gocd-server#64]
When I try to run with the host network, I get this error:

```
java.lang.RuntimeException: computer: computer: Try again
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:36)
	at com.thoughtworks.go.server.util.GoSslSocketConnector.getHostname(GoSslSocketConnector.java:101)
	at com.thoughtworks.go.server.util.GoSslSocketConnector.ensureX509Certificates(GoSslSocketConnector.java:91)
	at com.thoughtworks.go.server.util.GoSslSocketConnector.sslConnector(GoSslSocketConnector.java:56)
	at com.thoughtworks.go.server.util.GoSslSocketConnector.<init>(GoSslSocketConnector.java:52)
	at com.thoughtworks.go.server.Jetty9Server.sslConnector(Jetty9Server.java:145)
	at com.thoughtworks.go.server.Jetty9Server.configure(Jetty9Server.java:80)
	at com.thoughtworks.go.server.GoServer.configureServer(GoServer.java:84)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:104)
	at com.thoughtworks.gocd.Boot.main(Boot.java:55)
Caused by: java.net.UnknownHostException: computer: computer: Try again
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at com.thoughtworks.go.server.util.GoSslSocketConnector.getHostname(GoSslSocketConnector.java:99)
	... 15 more
Caused by: java.net.UnknownHostException: computer: Try again
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 16 more
```

Any reason why isn't this supported?

**Comment by ketan** [comment]
What's the command line arg you're using?

**Comment by vitorarins** [comment]
Hi @ketan, thanks for your response. I just ran the command from the README, but changing the ports exposure by `--net=host`. So this: `docker run -d --net=host gocd/gocd-server:v18.2.0`

**Comment by chadlwilson** [comment]
If this is till a concern/requirement, please open an issue at https://github.com/gocd/gocd
